apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/hongweiliu-tenant/my-app/devfile-sample-go-basic@sha256:df73fabb76e272720815d41c89f62dc660f86a43729e61f010a3bcff4378c40c
        name: my-go
        resources: {}
status: {}
