apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-beju
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/hongweiliu-tenant/my-app/devfile-sample-beju@sha256:fc2b7eafdf587c3aa30da2ff5ca32618da9e1837164e6b12c6f719151b1f2cd0
        name: my-nodejs
        resources: {}
status: {}
