apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-beju
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-beju
    app.kubernetes.io/part-of: my-app
  name: devfile-sample-beju
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-beju
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-beju
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/hongweiliu-tenant/my-app/devfile-sample-beju@sha256:fc2b7eafdf587c3aa30da2ff5ca32618da9e1837164e6b12c6f719151b1f2cd0
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
